global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'task-orchestrator-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'task-orchestrator-worker'
    static_configs:
      - targets: ['host.docker.internal:9091']
